# Generated by Django 4.2 on 2025-05-08 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=256, unique=True)),
                ("title", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.TextField()),
                ("image_url", models.TextField(blank=True, null=True)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventUserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("theatre_weight", models.FloatField(default=0.0)),
                ("rock_weight", models.FloatField(default=0.0)),
                ("performance_art_weight", models.FloatField(default=0.0)),
                ("rnb_weight", models.FloatField(default=0.0)),
                ("baseball_weight", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="EventUserInteractions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("clicked", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
