# Generated by Django 4.2 on 2025-05-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventuserpreferences",
            name="equestrian_weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="eventuserpreferences",
            name="football_weight",
            field=models.FloatField(default=0.0),
        ),
    ]
